spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cityadministration
    username: root
    password: "123"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  session:
    timeout: 30m
    store-type: jdbc
    jdbc:
      initialize-schema: always
  server:
    servlet:
      session:
        cookie:
          same-site: Lax
          secure: false
          http-only: true
          max-age: 1800
